### ISSUE TITLE
出现bug

### ISSUE THREAD

**Issue by loxs123** [liu-zichen/TreeMAN#1]
您好，我在运行您的代码（preprocess.py）时遇到了下面的问题，请问该如何解决呢？
Traceback (most recent call last):
  File "preprocess.py", line 397, in <module>
    p.preprocess_text()
  File "preprocess.py", line 244, in preprocess_text
    df_text = (pd.read_csv(f'{MIMIC_DIR}NOTEEVENTS.csv').query(
  File "/root/miniconda3/lib/python3.8/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/miniconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    return parser.read(nrows)
  File "/root/miniconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/root/miniconda3/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: EOF inside string starting at row 368644

**Comment by loxs123** [comment]
对不起打扰您了，是我的文件损坏了，现在已经好了
